// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQLgsoqGC9Gyu2LNldwoYq2XsMlcBWpaU',
    appId: '1:607200222812:android:e572d697279fe03fc09099',
    messagingSenderId: '607200222812',
    projectId: 'samchat-1116d',
    storageBucket: 'samchat-1116d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUkWmJDnUOVo6ORTVKyJOx4OjGzbS3BU',
    appId: '1:607200222812:ios:281d5088f728d21dc09099',
    messagingSenderId: '607200222812',
    projectId: 'samchat-1116d',
    storageBucket: 'samchat-1116d.firebasestorage.app',
    androidClientId: '607200222812-lb28l4bsnfu8li6qu9in0k3chv1ahcnh.apps.googleusercontent.com',
    iosClientId: '607200222812-pk2rd3m19pr17tgvpvsejdcva3r8bkn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.samChat',
  );

}